import Config

# Configure your database
config :heads_up, HeadsUp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "heads_up_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :heads_up, HeadsUpWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cvJqmFljNvkQPOMVfTIugjru1rdzUjTRQomKVPmsNCMFtYrKzsPX+er3WsJqubeA",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:heads_up, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:heads_up, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :heads_up, HeadsUpWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/heads_up_web/router\.ex$"E,
      ~r"lib/heads_up_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :heads_up, dev_routes: true

# Short scoring window in dev so you can watch a duel auto-settle on-device a
# couple of minutes after drafting (prod uses 24h). The worker still sweeps on
# its normal interval; `Settlement.settle_duel(id)` force-settles instantly.
config :heads_up, :scoring_window_seconds, 120

# Phase 5b — settle dev duels against the REAL ESPN WNBA feed. (Tests keep the
# deterministic Mock.) A normal 120s-window draft will find no FINAL games in
# that tiny window and settle 0–0; to test against a real game night, point the
# window at a past date: `HeadsUp.DevTools.settle_on_date(duel_id, ~D[2026-06-28])`
# or `mix heads_up.settle_on_date <duel_id> 2026-06-28`.
config :heads_up, :stats_providers, %{
  "wnba" => HeadsUp.Settlement.Stats.WnbaEspn,
  "mlb" => HeadsUp.Settlement.Stats.MlbEspn
}

# Fallback for any sport without a dedicated provider above.
config :heads_up, :stats_provider, HeadsUp.Settlement.Stats.WnbaEspn

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
